### ISSUE TITLE
Refreshing the riot logo

### ISSUE THREAD

**Issue by GianlucaGuarini** [riot/logo#3]
For the upcoming riot@4 release the source code was completely rewritten. I am working on a new website that will be clean and minimal mirroring the framework simple and clean API.

For the new riot version I would like to refresh also its logo keeping the red color but updating its style.
If you are a designer and you like riot you can contribute posting your proposal here and the logo with more 👍  will be picked as new official logo.

Thanks for your help.

**Comment by nibushibu** [comment]
How about this?

<img width="462" alt="riotjs-new-logo" src="https://user-images.githubusercontent.com/399949/53905812-d5518780-408c-11e9-9b3e-59d94bbfdf7c.png">

**Comment by GianlucaGuarini** [comment]
@nibushibu cool I like it. Thank you for your idea!

**Comment by nibushibu** [comment]
@GianlucaGuarini 
I have been thinking of redesigning the Riot logo more simple and symbolic (with my personal interest).
so I'm glad that I could show it here.

I'm also a front end engineer who uses Riot.js.
And I am grateful for your contribution to this project.

**Comment by caneco** [comment]
I don't see it much as a "Fire" but the "First" shape it's there!!!

**Really awesome logo!**

**Comment by nibushibu** [comment]
here is the other fist. ✊

<img width="426" alt="riot-new-logo-2" src="https://user-images.githubusercontent.com/399949/53976877-3b044900-414b-11e9-9812-e059eef2c27d.png">

**Comment by Infeligo** [comment]
> here is the other fist. 
> 
> <img alt="riot-new-logo-2" width="426" src="https://user-images.githubusercontent.com/399949/53976877-3b044900-414b-11e9-9812-e059eef2c27d.png">

That's [Rollup.JS](https://rollupjs.org/guide/en).

**Comment by GianlucaGuarini** [comment]
@nibushibu could you please make a PR against this repo with your [logo](https://github.com/riot/logo/issues/3#issuecomment-470231285) as svg file? I would like to try it in the new riot website template. Thanks

**Comment by nibushibu** [comment]
@GianlucaGuarini I just made a PR. Thanks! 
I'm looking forward to a new website! 🥳

https://github.com/riot/logo/pull/4

**Comment by nibushibu** [comment]
PR was sent, though I tried to improve a second idea a bit.
Because it was pointed out that it resembles the "Rollup".

<img width="426" alt="riot-new-logo-2-v2" src="https://user-images.githubusercontent.com/399949/54085755-b0a72980-4384-11e9-87d0-7cae75e74f18.png">

**Comment by GianlucaGuarini** [comment]
the new logo was merged many thanks to @nibushibu for his proposal and his creativity! https://github.com/riot/logo/pull/4
