### ISSUE TITLE
Module icons for branding

### ISSUE THREAD

**Issue by nibushibu** [riot/logo#8]
I have come up with a logo design for Riot.js modules.
This design is compatible with the Riot.js logo for v4 and above.
I think these would help people understand the functionality of Riot.js, which is divided into modules.

I will create a PR for this once I have adjusted the design a bit more.

![riotjs-module-icons-design](https://user-images.githubusercontent.com/399949/174445201-9a584998-a8ae-433c-9f59-82090296fc6f.png)

**Comment by nibushibu** [comment]
custom-elements are still under development, so I have distinguished them with a black color. (I'll fix the typo and lack of trailing s later.😅

**Comment by nibushibu** [comment]
@GianlucaGuarini Thank you for merging!
I plan to open PR for Adding a branding logs to official website, and I notice that I forgot designing to for `riotjs/hydrate` when I check current official site.
So I will try to add 'hydrate` logo first.
https://riot.js.org/#powerful-and-modular-ecosystem

By the way, I have made logos with a priority on announcing Riot features that may not be well known yet(I guess `animore` is a prime example 😉), So I have skipped  `compiler`,`parser`,`dom-bindings` that's internal modules for normal Riot.js compilation.
(but if they are important to you that you need a branding logo, I am willing to create that later.👌)

**Comment by GianlucaGuarini** [comment]
Thank you @nibushibu . I'd love to see the `@riotjs/compiler` as well if you have time for it. Just open a new PR when you are ready.

**Comment by nibushibu** [comment]
Thanks for your patience.
I also came up with branding logos for `parser`, `hydrate`, `compiler` and `dom-binding`.

![parser-logo-concept](https://user-images.githubusercontent.com/399949/189951633-8fa1ca44-3404-4521-8ada-777b4ff0bd90.jpg)
![hydrate-logo-concept](https://user-images.githubusercontent.com/399949/189951652-8535201f-bc2b-43ba-8446-48647abf4f53.jpg)
![compiler-logo-concept](https://user-images.githubusercontent.com/399949/189951675-02df6e0b-2616-45f2-921d-2570020fadf6.jpg)
![dom-binding-logo-concept](https://user-images.githubusercontent.com/399949/189951685-b63872e6-31f0-4235-8d34-35615bafb981.jpg)

**Comment by GianlucaGuarini** [comment]
@nibushibu your logos are awesome thank you! Please open a PR adding them as SVG. I guess that we can create a page on Riot.js listing all the ecosystem packages with your logos.

**Comment by nibushibu** [comment]
@GianlucaGuarini Thank you very much.
I'm glad to you like that logos. 
I’ll open PR after I’m fine-tuning the finishing touches on that logos in this weekend.

> I guess that we can create a page on Riot.js listing all the ecosystem packages with your logos.

that’s graet!
I also wanted to do it to get the word out about the Riot.js ecosystem. 
But I stumbled on setting up development environments(like Jekyll, etc.) and ended up not doing that yet.😇

I would be grateful if you could help me to add new branding logos on the official page as long as it is not too much of a burden for you.
(I will also prepare a single image of the entire ecosystem logo in the branding repository for this purpose.)

**Comment by GianlucaGuarini** [comment]
@nibushibu I run the Riot.js site using Bundler. Have you tried installing jekyll with it https://jekyllrb.com/tutorials/using-jekyll-with-bundler/ ?
